attribute preactivation_states missing in SaturationLogger
Traceback (most recent call last):
  File "tf_notebook.py", line 65, in <module>
    history = get_history(saturation_logger=saturation_logger, target_layer=target_layer)
  File "N:\traja-research\delve_utils.py", line 8, in get_history
    layer_history = saturation_logger.preactivation_states[target_layer]Traceback (most recent call last):
  File "tf_notebook.py", line 65, in <module>
    history = get_history(saturation_logger=saturation_logger, target_layer=target_layer)
  File "N:\traja-research\delve_utils.py", line 8, in get_history
    layer_history = saturation_logger.preactivation_states[target_layer]
AttributeError: 'SaturationLogger' object has no attribute 'preactivation_states'
AttributeError: 'SaturationLogger' object has no attribute 'preactivation_states'